name: inputtest
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^4.0.2
  url_launcher: ^6.0.9
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true